#!/usr/bin/env python3

import argparse

from rest_client.rest_client import rest_read, rest_stat
from utils.utils import save_file, is_valid_url



def parse_arguments():
    parser = argparse.ArgumentParser(description="File Client CLI", prog="file-client")
    parser.add_argument("action", choices=["stat", "read"], help="Action to perform")
    parser.add_argument("uuid", help="UUID of the file")
    parser.add_argument("--backend", choices=["grpc", "rest"], default="grpc", help="Which backend to use")
    parser.add_argument("--grpc-server", default="localhost:50051", help="gRPC server address") 
    parser.add_argument("--base-url", default="http://localhost:8000/", help="Base URL for REST server")
    parser.add_argument("--output", default="-", help="Output file (default is stdout)")
    return parser.parse_args()


if __name__ == "__main__":


#invalid url, need to validate URL

    args = parse_arguments()
    if not is_valid_url(args.base_url):
        raise ValueError(f"Please provide valid URL adress for RESTAPI endpoint.\n{args.base_url} is not valid adress.")
    
    if args.backend == "grpc":
        raise Exception("Grpc method not implemented. Use rest method again. Do not forget to specify \"base-url\" parameter!")
    
    elif args.backend == "rest":  #Theoretically there is the elif statement useless, because we have only two options, and first option is validated above.

        if args.action == "stat":
            result = rest_stat(args.uuid, args.base_url) #There only print

        elif args.action == "read": #There save or redirect into STDOUT /STDIN and STDERR are ommited
            result = rest_read(args.uuid, args.base_url) 
            if result:
                if (not args.output):
                    print("Output file was not specified. Using default value \"-\" to output content into STDOUT")
                    print(result)
                elif (args.output != "-"):
                    save_file(filename=args.output, content=result)
                else:
                    print(result)

        #no need to else, because argparse will eliminate incorrect options.